rewriteconfig: false
#The name of the world
world: world
#The motd will have two lines. This one, and an info line. You may use & for colors.
motd: '&aA &c&lNubes&b&lHG &aServer'
#Whether the world should regenerate
regenerate: true
#Time the timer should count down from before the game starts
pregamedelay: 180
#Time the timer should go to when not enough players
retime: 120
#Minimum amount of players required to start
minimum: 2
#Time the feast should start
feast: 720
#Should soup heal?
soup: true
#How much should soup heal?
heals: 7
#Wether to use the built-in kits or not
builtin: true
#Disabled Kits
disabled:
 - Kitname

#Whether to use mysql or not - this is currently the only option for saving statistics
mysql: false
host: '127.0.0.1'
port: 3306
database: 'db_name'
table: 'HG'
user: 'Bob'
password: 'IlluminatiConfirmed'