name: NubesHG
author: NubeBuster
version: 1.5
main: me.Mark.HG.HG
website: https://www.spigotmc.org/resources/nubes-hunger-games.9062/
load: Startup
softdepend: [TerrainControl]
permissions:
  hg.kits.*:
    description: Gives permission to all kits
    default: true
  hg.kits.none:
    default: true
  hg.*:
    children:
      hg.start: true
      hg.ftime: true
      hg.ffeast: true
      hg.gm: true
      hg.inv: true
  hg.start:
    default: op
  hg.ftime:
    default: op
  hg.ffeast:
    default: op
  hg.gm:
    default: op
  hg.inv:
    description: Gives permission to view inventories as spectator
    default: true
commands:
  kit:
    description: Choose what kit to play with!
    aliases: [class]
  go:
  lag:
  gm:
  feast:
  start:
  forcetime:
    aliases: [ftime]
  forcefeast:
    aliases: [ffeast]
  invsee:
    aliases: [inv]
  spawn:
  hg: