name: NubesHG
author: NubeBuster
version: 1.9
main: me.Mark.HG.HG
website: https://www.spigotmc.org/resources/nubes-hunger-games.9062/
load: Startup
softdepend: [TerrainControl]
permissions:
  hg.kits.*:
    description: Gives permission to all kits
    default: true
  hg.kits.none:
    default: true
  hg.*:
    children:
      hg.start: true
      hg.ftime: true
      hg.ffeast: true
      hg.gm: true
      hg.inv: true
  hg.start:
    default: op
  hg.ftime:
    default: op
  hg.ffeast:
    default: op
  hg.gm:
    default: op
  hg.inv:
    description: Gives permission to view inventories as spectator
    default: true
commands:
  kit:
    description: Choose what kit to play with!
    aliases: [class]
  spectate:
    description: Spectate a player
    aliases: [go, spec]
  lag:
    description: Displays the ticks per second in the last 5 seconds
  gm:
    description: Toggle between gamemode CREATIVE and SURVIVAL
  feast:
    description: Point your compass to the feast
  start:
    description: Force the game to start
  forcetime:
    description: Force the game time
    aliases: [ftime]
  forcefeast:
    description: Force the feast to start
    aliases: [ffeast]
  invsee:
    description: Show someone's inventory
    aliases: [inv]
  spawn:
    description: Teleport to a random location in the game to make up a plan
  hg:
    description: Displays information about the plugin